version: '2'
services:
  db:
    image: mysql:5.7
    env_file:
      - ipa-web.env
    ports:
      - 3306:3306
  spring:
    build:
      context: ./
      dockerfile: Dockerfile-spring
    volumes:
        - ./certs/dw.dss.ucdavis.edu.cer:/dw.dss.ucdavis.edu.cer
    env_file:
      - ipa-web.env
    depends_on:
      - db
  web:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    volumes:
        - ./certs/api_ipa_nginx.cer:/etc/ssl/private/api_ipa_nginx.cer
        - ./certs/api_ipa_nginx.key:/etc/ssl/private/api_ipa_nginx.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - spring
