version: '2'
services:
  db:
    image: mysql:5.7
  spring:
    build:
      context: ./
      dockerfile: Dockerfile-spring
    env_file:
      - ipa-web.env
    depends_on:
      - db
  web:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - 443:443
    depends_on:
      - spring
